// BORRO — control panel sections.

const RATIOS = {
  '2:1': '2:1',
  '16:9': '16:9',
  '3:2': '3:2',
  '4:3': '4:3',
  '5:4': '5:4',
  '1:1': '1:1',
  '4:5': '4:5',
  '3:4': '3:4',
  '2:3': '2:3',
  '9:16': '9:16',
  '1:2': '1:2',
};

const BLEND_MODES = {
  STANDARD: 'BLEND',
  ADD: 'ADD',
  SCREEN: 'SCREEN',
  OVERLAY: 'OVERLAY',
  MULTIPLY: 'MULTIPLY',
  LIGHTEST: 'LIGHTEST',
  DARKEST: 'DARKEST',
  'HARD LIGHT': 'HARD_LIGHT',
  'SOFT LIGHT': 'SOFT_LIGHT',
  EXCLUSION: 'EXCLUSION',
  DIFFERENCE: 'DIFFERENCE',
  XOR: 'XOR',
};

export const SECTIONS = [
  {
    title: 'Canvas',
    controls: [
      { id: 'bo-ratio', type: 'select', label: 'Canvas Ratio', path: 'cnv.ratio', options: RATIOS, regen: 'canvas' },
      { id: 'bo-scale-x', type: 'slider', label: 'Content Scale X', path: 'cnv.scale.x', min: -0.5, max: 0.5, step: 0.01 },
      { id: 'bo-scale-y', type: 'slider', label: 'Content Scale Y', path: 'cnv.scale.y', min: -0.5, max: 0.5, step: 0.01 },
      {
        id: 'bo-bg-type',
        type: 'select',
        label: 'Background',
        path: 'palette.bg.type',
        options: { 'Random Color': 'random', 'Custom Color': 'custom' },
        regen: 'bg',
      },
      { id: 'bo-bg-color', type: 'color', label: 'Back Color', path: 'palette.bg.color' },
      { id: 'bo-seed', type: 'slider', label: 'Noise Seed', path: 'cnv.seed.base', min: 0, max: 10000, step: 1, regen: 'seed' },
      { id: 'bo-random', type: 'button', label: 'Random Parameters' },
    ],
  },
  {
    title: 'Form',
    controls: [
      {
        id: 'bo-form-type',
        type: 'select',
        label: 'Shape Type',
        path: 'form.type',
        options: { Rectangle: 'form', 'Custom SVG (from preset)': 'custom' },
        regen: 'forms',
      },
      {
        id: 'bo-svg-sort',
        type: 'select',
        label: 'Sort Order',
        path: 'svg.sort',
        options: { Random: 'random', Ascending: 'asc', Descending: 'desc' },
        regen: 'forms',
      },
      { id: 'bo-svg-seed', type: 'slider', label: 'Shapes Seed', path: 'svg.seed', min: 0, max: 10000, step: 1, regen: 'forms' },
      { id: 'bo-count-x', type: 'slider', label: 'Shape Amount X', path: 'form.count.x', min: 1, max: 10, step: 1, regen: 'forms' },
      { id: 'bo-count-y', type: 'slider', label: 'Shape Amount Y', path: 'form.count.y', min: 1, max: 10, step: 1, regen: 'forms' },
      {
        id: 'bo-corners-type',
        type: 'select',
        label: 'Corners Type',
        path: 'form.corners.type',
        options: { 'Uniform Level': 'uniform', 'Random Level': 'random' },
        regen: 'forms',
      },
      { id: 'bo-corners-level', type: 'slider', label: 'Round Corners', path: 'form.corners.level', min: 0, max: 100, step: 1 },
      { id: 'bo-corners-seed', type: 'slider', label: 'Corners Seed', path: 'form.corners.seed', min: 0, max: 10000, step: 1, regen: 'forms' },
      { id: 'bo-random-count', type: 'button', label: 'Random Form Settings' },
    ],
  },
  {
    title: 'Size',
    controls: [
      {
        id: 'bo-size-type',
        type: 'select',
        label: 'Size Type',
        path: 'form.size.type',
        options: {
          'XY Related (Canvas / Forms Num)': 'canvas',
          'XY Related (Canvas / 2)': 'default',
          'Uniform (Canvas / 2)': 'uniform',
        },
        regen: 'forms',
      },
      { id: 'bo-size-uni', type: 'slider', label: 'Size Multiplier', path: 'form.size.uni', min: 0, max: 2, step: 0.01 },
      { id: 'bo-size-x', type: 'slider', label: 'Size Multiplier X', path: 'form.size.x', min: 0, max: 2, step: 0.01 },
      { id: 'bo-size-y', type: 'slider', label: 'Size Multiplier Y', path: 'form.size.y', min: 0, max: 2, step: 0.01 },
      {
        id: 'bo-size-random-mode',
        type: 'select',
        label: 'Random Mode',
        path: 'form.size.random.mode',
        options: { 'Independent For X/Y': 'independent', 'Uniform Value': 'uniform' },
        regen: 'forms',
      },
      { id: 'bo-size-random-x', type: 'slider', label: 'Random Level X', path: 'form.size.random.x', min: 0, max: 1, step: 0.01, regen: 'forms' },
      { id: 'bo-size-random-y', type: 'slider', label: 'Random Level Y', path: 'form.size.random.y', min: 0, max: 1, step: 0.01, regen: 'forms' },
      { id: 'bo-size-seed', type: 'slider', label: 'Random Seed', path: 'form.size.seed', min: 0, max: 10000, step: 1, regen: 'forms' },
      { id: 'bo-random-size', type: 'button', label: 'Random Size Settings' },
    ],
  },
  {
    title: 'Offset',
    controls: [
      { id: 'bo-offset-x', type: 'slider', label: 'Form Offset X', path: 'form.offset.x', min: -1, max: 1, step: 0.01 },
      { id: 'bo-offset-y', type: 'slider', label: 'Form Offset Y', path: 'form.offset.y', min: -1, max: 1, step: 0.01 },
      { id: 'bo-offset-random', type: 'slider', label: 'Random Level', path: 'form.offset.random', min: 0, max: 1, step: 0.01 },
      { id: 'bo-offset-seed', type: 'slider', label: 'Random Seed', path: 'form.offset.seed', min: 0, max: 10000, step: 1, regen: 'forms' },
      { id: 'bo-random-offset', type: 'button', label: 'Random Offset Settings' },
    ],
  },
  {
    title: 'Angle',
    controls: [
      { id: 'bo-angle-range', type: 'slider', label: 'Base Angle', path: 'form.angle.range', min: -180, max: 180, step: 1 },
      {
        id: 'bo-angle-mode',
        type: 'select',
        label: 'Random Mode',
        path: 'form.angle.mode',
        options: { 'Random Angle': 'random', 'Right Angle': 'right' },
        regen: 'forms',
      },
      { id: 'bo-angle-random', type: 'slider', label: 'Random Level', path: 'form.angle.random', min: 0, max: 1, step: 0.01, regen: 'forms' },
      { id: 'bo-angle-seed', type: 'slider', label: 'Random Seed', path: 'form.angle.seed', min: 0, max: 10000, step: 1, regen: 'forms' },
      { id: 'bo-random-angle', type: 'button', label: 'Random Angle Settings' },
    ],
  },
  {
    title: 'Form Blur',
    controls: [
      { id: 'bo-blur-min', type: 'slider', label: 'Blur Range Min', path: 'form.blur.range.min', min: 0, max: 150, step: 1, regen: 'forms' },
      { id: 'bo-blur-max', type: 'slider', label: 'Blur Range Max', path: 'form.blur.range.max', min: 0, max: 150, step: 1, regen: 'forms' },
      { id: 'bo-blur-freq', type: 'slider', label: 'Frequency', path: 'form.blur.freq', min: 0, max: 1, step: 0.01 },
      { id: 'bo-blur-seed', type: 'slider', label: 'Random Seed', path: 'form.blur.seed', min: 0, max: 10000, step: 1, regen: 'forms' },
      { id: 'bo-random-blur', type: 'button', label: 'Random Blur Settings' },
    ],
  },
  {
    title: 'Color Blend',
    controls: [
      { id: 'bo-blend-min', type: 'slider', label: 'Blend Range Min', path: 'form.blend.range.min', min: 0, max: 1, step: 0.01 },
      { id: 'bo-blend-max', type: 'slider', label: 'Blend Range Max', path: 'form.blend.range.max', min: 0, max: 1, step: 0.01 },
      { id: 'bo-blend-freq', type: 'slider', label: 'Frequency', path: 'form.blend.freq', min: 0, max: 1, step: 0.01 },
      { id: 'bo-blend-seed', type: 'slider', label: 'Random Seed', path: 'form.blend.seed', min: 0, max: 10000, step: 1, regen: 'forms' },
      { id: 'bo-random-blend', type: 'button', label: 'Random Blend Settings' },
    ],
  },
  {
    title: 'Palette',
    controls: [
      { id: 'bo-blend-mode', type: 'select', label: 'Blend Mode', path: 'cnv.blend', options: BLEND_MODES },
      {
        id: 'bo-palette-type',
        type: 'select',
        label: 'Palette Type',
        path: 'palette.type',
        options: { Generative: 'generative', 'Defined Palettes': 'defined', 'Custom Colors': 'custom' },
        regen: 'palette',
      },
      { id: 'bo-palette-index', type: 'slider', label: 'Palette Number', path: 'palette.custom.index', min: 1, max: 150, step: 1, regen: 'palette' },
      { id: 'bo-populate', type: 'button', label: 'Populate Colors To Custom' },
      { id: 'bo-color-0', type: 'color', label: 'Color 1', path: 'palette.custom.color.0', regen: 'palette' },
      { id: 'bo-color-1', type: 'color', label: 'Color 2', path: 'palette.custom.color.1', regen: 'palette' },
      { id: 'bo-color-2', type: 'color', label: 'Color 3', path: 'palette.custom.color.2', regen: 'palette' },
      { id: 'bo-color-3', type: 'color', label: 'Color 4', path: 'palette.custom.color.3', regen: 'palette' },
      { id: 'bo-color-4', type: 'color', label: 'Color 5', path: 'palette.custom.color.4', regen: 'palette' },
      { id: 'bo-shuffle-colors', type: 'button', label: 'Shuffle Colors in Palette' },
      { id: 'bo-off-x', type: 'slider', label: 'Offset R', path: 'palette.offset.x', min: 0, max: 1, step: 0.01 },
      { id: 'bo-off-y', type: 'slider', label: 'Offset G', path: 'palette.offset.y', min: 0, max: 1, step: 0.01 },
      { id: 'bo-off-z', type: 'slider', label: 'Offset B', path: 'palette.offset.z', min: 0, max: 1, step: 0.01 },
      { id: 'bo-amp-x', type: 'slider', label: 'Amplify R', path: 'palette.amp.x', min: 0, max: 1, step: 0.01 },
      { id: 'bo-amp-y', type: 'slider', label: 'Amplify G', path: 'palette.amp.y', min: 0, max: 1, step: 0.01 },
      { id: 'bo-amp-z', type: 'slider', label: 'Amplify B', path: 'palette.amp.z', min: 0, max: 1, step: 0.01 },
      { id: 'bo-freq-x', type: 'slider', label: 'Freq R', path: 'palette.freq.x', min: 0, max: 3.14, step: 0.01 },
      { id: 'bo-freq-y', type: 'slider', label: 'Freq G', path: 'palette.freq.y', min: 0, max: 3.14, step: 0.01 },
      { id: 'bo-freq-z', type: 'slider', label: 'Freq B', path: 'palette.freq.z', min: 0, max: 3.14, step: 0.01 },
      { id: 'bo-phase-x', type: 'slider', label: 'Phase R', path: 'palette.phase.x', min: -1, max: 1, step: 0.01 },
      { id: 'bo-phase-y', type: 'slider', label: 'Phase G', path: 'palette.phase.y', min: -1, max: 1, step: 0.01 },
      { id: 'bo-phase-z', type: 'slider', label: 'Phase B', path: 'palette.phase.z', min: -1, max: 1, step: 0.01 },
      { id: 'bo-random-palette', type: 'button', label: 'Random Palette Settings' },
    ],
  },
  {
    title: 'Post Processing',
    controls: [
      { id: 'bo-post-blur', type: 'slider', label: 'Fullscreen Blur', path: 'post.blur.radius', min: 0, max: 10, step: 0.1, regen: 'buffers' },
      { id: 'bo-post-bright', type: 'slider', label: 'Brightness Level', path: 'post.color.brightness', min: -0.5, max: 0.5, step: 0.01 },
      { id: 'bo-post-contrast', type: 'slider', label: 'Contrast Level', path: 'post.color.contrast', min: 0, max: 3, step: 0.01 },
      { id: 'bo-grain-scale', type: 'slider', label: 'Grain Scale', path: 'post.grain.scale', min: 0.5, max: 2, step: 0.01, regen: 'buffers' },
      { id: 'bo-grain-opacity', type: 'slider', label: 'Grain Opacity', path: 'post.grain.opacity', min: 0, max: 1, step: 0.01 },
      { id: 'bo-grain-bright', type: 'slider', label: 'Grain Brightness', path: 'post.grain.brightness', min: 0.1, max: 1, step: 0.01 },
      { id: 'bo-grain-contrast', type: 'slider', label: 'Grain Contrast', path: 'post.grain.contrast', min: 0.1, max: 1, step: 0.01 },
      { id: 'bo-grain-freq', type: 'slider', label: 'Grain Frequency', path: 'post.grain.freq', min: 0, max: 1, step: 0.01 },
    ],
  },
];
