// COPO — control panel sections.

import { shapeTypes } from './shapes.js';

const RATIOS = {
  '2:1': '2:1',
  '16:9': '16:9',
  '3:2': '3:2',
  '4:3': '4:3',
  '5:4': '5:4',
  '1:1': '1:1',
  '4:5': '4:5',
  '3:4': '3:4',
  '2:3': '2:3',
  '9:16': '9:16',
  '1:2': '1:2',
};

const EASE_OPTIONS = {
  None: 'none',
  Linear: 'Linear',
  'Sine In': 'Sine In',
  'Sine Out': 'Sine Out',
  'Sine In Out': 'Sine In Out',
  'Quad In': 'Quad In',
  'Quad Out': 'Quad Out',
  'Quad In Out': 'Quad In Out',
  'Cubic In': 'Cubic In',
  'Cubic Out': 'Cubic Out',
  'Cubic In Out': 'Cubic In Out',
  'Expo In': 'Expo In',
  'Expo Out': 'Expo Out',
  'Expo In Out': 'Expo In Out',
  'Circ In': 'Circ In',
  'Circ Out': 'Circ Out',
  'Circ In Out': 'Circ In Out',
};

const BLEND_MODES = {
  Normal: 'source-over',
  XOR: 'xor',
  Lighter: 'lighter',
  Multiply: 'multiply',
  Screen: 'screen',
  Overlay: 'overlay',
  Darken: 'darken',
  Lighten: 'lighten',
  'Color Dodge': 'color-dodge',
  'Color Burn': 'color-burn',
  'Hard Light': 'hard-light',
  'Soft Light': 'soft-light',
  Exclusion: 'exclusion',
  Difference: 'difference',
};

const SHAPE_OPTIONS = Object.fromEntries(
  Object.entries(shapeTypes).filter(([, v]) => v !== 'custom')
);

export const SECTIONS = [
  {
    title: 'Canvas',
    controls: [
      { id: 'co-ratio', type: 'select', label: 'Canvas Ratio', path: 'cnv.ratio', options: RATIOS, regen: 'canvas' },
      { id: 'co-scale', type: 'slider', label: 'Canvas Scale', path: 'cnv.scale', min: 0.5, max: 2, step: 0.01, regen: 'frame' },
      {
        id: 'co-bg-mode',
        type: 'select',
        label: 'Background',
        path: 'cnv.bg.mode',
        options: { Custom: 'custom', Transparent: 'transparent' },
      },
      { id: 'co-bg-color', type: 'color', label: 'Canvas Color', path: 'cnv.bg.custom' },
      { id: 'co-animation', type: 'check', label: 'Animation', path: 'cnv.animation', regen: 'frame' },
      {
        id: 'co-motion-mode',
        type: 'select',
        label: 'Motion Mode',
        path: 'params.motion.mode',
        options: { 'Scaling (One Way)': 'oneway', 'Scaling (Loop)': 'loop', 'Noise (Loop)': 'noise' },
        regen: 'frame',
      },
      { id: 'co-motion-amp', type: 'slider', label: 'Amplify Level', path: 'params.motion.amp', min: -100, max: 100, step: 1, regen: 'frame' },
    ],
  },
  {
    title: 'Style',
    controls: [
      {
        id: 'co-style',
        type: 'select',
        label: 'Render Style',
        path: 'params.color.style',
        options: { Fill: 'fill', Stroke: 'stroke', Mixed: 'mixed' },
        regen: 'frame',
      },
      { id: 'co-mixed', type: 'slider', label: 'Fill/Stroke Ratio', path: 'params.color.mixed', min: 0, max: 1, step: 0.01, regen: 'frame' },
      { id: 'co-stroke-width', type: 'slider', label: 'Stroke Width', path: 'params.stroke.width', min: 0.25, max: 3, step: 0.05, regen: 'frame' },
      { id: 'co-stroke-scale', type: 'check', label: 'Stroke Scale', path: 'params.stroke.scale', regen: 'frame' },
      { id: 'co-blend', type: 'select', label: 'Blend Type', path: 'params.color.blend', options: BLEND_MODES, regen: 'frame' },
      {
        id: 'co-color-type',
        type: 'select',
        label: 'Color Type',
        path: 'params.color.type',
        options: { 'Solid Color': 'color', 'Palette Sequence': 'sequence', 'Palette Transition': 'transition' },
        regen: 'palette',
      },
      { id: 'co-base-color', type: 'color', label: 'Shape Color', path: 'params.color.base', regen: 'frame' },
      { id: 'co-color-0', type: 'color', label: 'Color 1', path: 'palette.array.0', regen: 'palette' },
      { id: 'co-color-1', type: 'color', label: 'Color 2', path: 'palette.array.1', regen: 'palette' },
      { id: 'co-color-2', type: 'color', label: 'Color 3', path: 'palette.array.2', regen: 'palette' },
      { id: 'co-color-3', type: 'color', label: 'Color 4', path: 'palette.array.3', regen: 'palette' },
      { id: 'co-color-4', type: 'color', label: 'Color 5', path: 'palette.array.4', regen: 'palette' },
      { id: 'co-random-palette', type: 'button', label: 'Random Palette' },
      { id: 'co-shuffle-palette', type: 'button', label: 'Shuffle Colors' },
    ],
  },
  {
    title: 'Pattern',
    controls: [
      { id: 'co-cells-x', type: 'slider', label: 'Pattern Cells X', path: 'pattern.cells.x', min: 1, max: 16, step: 1, regen: 'frame' },
      { id: 'co-cells-y', type: 'slider', label: 'Pattern Cells Y', path: 'pattern.cells.y', min: 1, max: 16, step: 1, regen: 'frame' },
      { id: 'co-offset-x', type: 'slider', label: 'Cell Offset X', path: 'pattern.offset.x', min: -1, max: 1, step: 0.01, regen: 'frame' },
      { id: 'co-offset-y', type: 'slider', label: 'Cell Offset Y', path: 'pattern.offset.y', min: -1, max: 1, step: 0.01, regen: 'frame' },
      { id: 'co-pattern-seed', type: 'slider', label: 'Pattern Seed', path: 'pattern.seed.value', min: -1, max: 1, step: 0.01, regen: 'frame' },
      { id: 'co-seed-random', type: 'slider', label: 'Seed Random', path: 'pattern.seed.random', min: 0, max: 5, step: 0.01, regen: 'frame' },
      { id: 'co-cell-rotate', type: 'slider', label: 'Cell Rotation', path: 'pattern.rotate', min: -1, max: 1, step: 0.01, regen: 'frame' },
    ],
  },
  {
    title: 'Shape',
    controls: [
      { id: 'co-shape', type: 'select', label: 'Shape Type', path: 'shape.type', options: SHAPE_OPTIONS, regen: 'shape' },
      { id: 'co-grid-x', type: 'slider', label: 'Grid Mapping X', path: 'params.grid.x', min: 1, max: 16, step: 1, regen: 'frame' },
      { id: 'co-grid-y', type: 'slider', label: 'Grid Mapping Y', path: 'params.grid.y', min: 1, max: 16, step: 1, regen: 'frame' },
      { id: 'co-count', type: 'slider', label: 'Shape Count', path: 'params.count.value', min: 500, max: 16000, step: 25, regen: 'frame' },
      { id: 'co-shape-scale', type: 'slider', label: 'Shape Scale', path: 'params.scale.value', min: 0.5, max: 10, step: 0.05, regen: 'frame' },
      { id: 'co-scale-power', type: 'slider', label: 'Scale Power', path: 'params.scale.power', min: 0, max: 5, step: 0.05, regen: 'frame' },
      { id: 'co-scale-ease', type: 'select', label: 'Scaling Ease', path: 'params.scale.easeType', options: EASE_OPTIONS, regen: 'frame' },
      { id: 'co-scale-ease-offset', type: 'slider', label: 'Easing Offset', path: 'params.scale.easeOffset', min: -1, max: 1, step: 0.01, regen: 'frame' },
      { id: 'co-rotate-shape', type: 'slider', label: 'Base Rotation', path: 'params.rotate.shape', min: -1, max: 1, step: 0.01, regen: 'frame' },
      { id: 'co-rotate-mult', type: 'slider', label: 'Angle Multiplier', path: 'params.rotate.mult', min: -3, max: 3, step: 0.01, regen: 'frame' },
    ],
  },
  {
    title: 'Noise',
    controls: [
      { id: 'co-seed', type: 'slider', label: 'Noise Seed', path: 'seed.value', min: 0, max: 100000, step: 1, regen: 'seed' },
      { id: 'co-gen-seed', type: 'button', label: 'Generate Noise Seed' },
      {
        id: 'co-symmetry',
        type: 'select',
        label: 'Symmetry',
        path: 'params.branch.symmetry',
        options: { Standard: 'standard', Mirrored: 'mirror' },
        regen: 'frame',
      },
      { id: 'co-branch-amount', type: 'slider', label: 'Branch Amount', path: 'params.branch.amount', min: 0, max: 10, step: 0.1, regen: 'frame' },
      { id: 'co-branch-angle', type: 'slider', label: 'Branch Angle', path: 'params.branch.angle', min: 0, max: 2, step: 0.01, regen: 'frame' },
      {
        id: 'co-freq-mode',
        type: 'select',
        label: 'Freq Mode',
        path: 'params.freq.mode',
        options: { Sin: 'sin', Cos: 'cos' },
        regen: 'frame',
      },
      { id: 'co-freq-ease', type: 'select', label: 'Freq Easing', path: 'params.freq.easeType', options: EASE_OPTIONS, regen: 'frame' },
      { id: 'co-freq-ease-offset', type: 'slider', label: 'Easing Offset', path: 'params.freq.easeOffset', min: -1, max: 1, step: 0.01, regen: 'frame' },
      { id: 'co-freq-layers', type: 'slider', label: 'Freq Layers', path: 'params.freq.layers', min: 2, max: 16, step: 1, regen: 'palette' },
      { id: 'co-freq-base', type: 'slider', label: 'Freq Base', path: 'params.freq.base', min: 0.01, max: 1, step: 0.01, regen: 'frame' },
      { id: 'co-freq-amp', type: 'slider', label: 'Freq Amplify', path: 'params.freq.amp', min: 0.01, max: 1, step: 0.01, regen: 'frame' },
    ],
  },
  {
    title: 'Swirl',
    controls: [
      {
        id: 'co-swirl-mode',
        type: 'select',
        label: 'Swirl Mode',
        path: 'params.swirl.mode',
        options: { None: 'none', 'Wave Effect': 'wave', 'Rotary Effect': 'rotary' },
        regen: 'frame',
      },
      { id: 'co-swirl-base', type: 'slider', label: 'Base Swirl', path: 'params.swirl.base', min: -1, max: 1, step: 0.01, regen: 'frame' },
      { id: 'co-swirl-amp', type: 'slider', label: 'Amplify Effect', path: 'params.swirl.amp', min: -1, max: 1, step: 0.01, regen: 'frame' },
      { id: 'co-swirl-freq', type: 'slider', label: 'Frequency', path: 'params.swirl.freq', min: 0.05, max: 1, step: 0.01, regen: 'frame' },
    ],
  },
  {
    title: 'Mask',
    controls: [
      {
        id: 'co-mask-mode',
        type: 'select',
        label: 'Mask Type',
        path: 'mask.mode',
        options: { None: 'none', Parameteric: 'parametric', 'Raster Image': 'image' },
        regen: 'frame',
      },
      {
        id: 'co-mask-branch-mode',
        type: 'select',
        label: 'Branch Mode',
        path: 'mask.branchMode',
        options: { 'Ignore Noise Branch Angle': 'ignore', 'Apply Noise Branch Angle': 'apply' },
        regen: 'frame',
      },
      { id: 'co-mask-branch', type: 'slider', label: 'Add Branches', path: 'mask.branch', min: 0, max: 12, step: 1, regen: 'frame' },
      { id: 'co-mask-round', type: 'check', label: 'Round Branches', path: 'mask.branchRound', regen: 'frame' },
      { id: 'co-mask-min', type: 'slider', label: 'Mask Margin Min', path: 'mask.margin.min', min: 0, max: 1, step: 0.01, regen: 'frame' },
      { id: 'co-mask-max', type: 'slider', label: 'Mask Margin Max', path: 'mask.margin.max', min: 0, max: 1, step: 0.01, regen: 'frame' },
      { id: 'co-mask-upload', type: 'button', label: 'Upload Mask Image' },
      { id: 'co-mask-scale', type: 'slider', label: 'Image Scale', path: 'mask.image.scale', min: 0.5, max: 2, step: 0.01, regen: 'frame' },
      { id: 'co-mask-bright', type: 'slider', label: 'Brightness', path: 'mask.image.brightness', min: -0.5, max: 0.5, step: 0.01, regen: 'frame' },
      { id: 'co-mask-contrast', type: 'slider', label: 'Contrast', path: 'mask.image.contrast', min: 0.5, max: 5, step: 0.01, regen: 'frame' },
      { id: 'co-mask-invert-light', type: 'check', label: 'Invert Lights', path: 'mask.image.invert.light', regen: 'frame' },
      { id: 'co-mask-invert-alpha', type: 'check', label: 'Invert Alpha', path: 'mask.image.invert.alpha', regen: 'frame' },
    ],
  },
];
